### ISSUE TITLE
Extending gem to work with RuboCop?

### ISSUE THREAD

**Issue by thomthom** [ukoloff/appveyor-worker#3]
I was wondering if there are ways to extend this gem to support other reporters?

Right now I'm looking at getting RuboCop reports reported on AppVeyor.

Is there a way I can create a gem that leverage the existing plumbing of this gem to provide a new source for reports?

Or would it be of interest an PR that integrate it directly into this gem?

**Comment by ukoloff** [comment]
I'm not sure that mixing these two functionalities is a good idea.

My gem passes results of regular tests to AppVeyor. Your idea (as far as I undestand it) is to run RuboCop against source files and report failures to AppVeyor. It is quite resonable,  but it should be separate gem or whatever.

You can always fallback to my gem to actually send information to AppVeyor (using `AppVeyor::Worker::test` method), look [here](/ukoloff/appveyor-worker/blob/master/lib/minitest/appveyor_plugin.rb) or [here](/ukoloff/appveyor-worker/blob/master/lib/appveyor/worker/rspec.rb) for examples.

So, you should better make your own regular gem, referencing my gem and using its method(s).

**Comment by thomthom** [comment]
Yea, what you say is reasonable. I was on the fence about this myself, as RuboCop isn't unit tests.

> So, you should better make your own regular gem, referencing my gem and using its method(s).

That works for me.
